name: Node.js Package

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: npm build
       
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/
      - run: pnpm install --frozen-lockfile
      - run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
